<a href="https://colab.research.google.com/github/jinexus1/numpy/blob/main/numpy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import numpy as np

In [32]:

a=np.array([1,2,3,4],dtype='int32')
print(a)

[1 2 3 4]


In [33]:
a.ndim


1

In [34]:
a.shape


(4,)

In [35]:
a.dtype


dtype('int32')

In [36]:
a.itemsize

4

In [37]:
a.nbytes

16

# New Section
Accessing and changing specific elements, rows, column,etc

In [38]:
import numpy as np


In [48]:
arr = np.array([[1, 2, 3, 4,8,9], [4, 5, 6, 7,11,12]])

print(arr)

[[ 1  2  3  4  8  9]
 [ 4  5  6  7 11 12]]


In [40]:
arr.shape


(2, 4)

get a specific element[r,c]

In [41]:
arr[1,1]

5

get a specific row

In [42]:
arr[0,:]

array([1, 2, 3, 4])

get a specific column

In [43]:
arr[:,1]

array([2, 5])

get fancy[rowNumber,startIndex:endIndex:stepIndex]

In [44]:
arr[0,1::1]

array([2, 3, 4])

In [45]:
arr[0, 1:-1:2]

array([2])

In [50]:
arr[1,5]=10
print(arr)

arr[:,2]=[1,2]
print(arr)

[[ 1  2  1  4  8  9]
 [ 4  5  2  7 11 10]]


3d array

In [53]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[12,13],[14,15]]])
print(b)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[12 13]
  [14 15]]]


Initializing different types of arrays

all zero matrix

In [54]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [56]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Mathematics

operation on each element of array

In [57]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [58]:
a-2
print(a)

[1 2 3 4]


In [59]:
a-2

array([-1,  0,  1,  2])

In [60]:
a+2

array([3, 4, 5, 6])

In [61]:
a*2

array([2, 4, 6, 8])

In [62]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [65]:
b=np.array([4,5,3,7])
a+b

array([ 5,  7,  6, 11])